version: '3'

services:
  node_1:
    container_name: node_1
    build: .
    networks:
      - polygon-local-network
    volumes:
      - node-1-data:/usr/src/polygon/data
      - shared-data:/usr/src/polygon/shared
  node_2:
    container_name: node_2
    build: .
    networks:
      - polygon-local-network
    volumes:
      - node-2-data:/usr/src/polygon/data
      - shared-data:/usr/src/polygon/shared
  node_3:
    container_name: node_3
    build: .
    networks:
      - polygon-local-network
    volumes:
      - node-3-data:/usr/src/polygon/data
      - shared-data:/usr/src/polygon/shared
  node_4:
    container_name: node_4
    build: .
    networks:
      - polygon-local-network
    volumes:
      - node-4-data:/usr/src/polygon/data
      - shared-data:/usr/src/polygon/shared

networks:
  polygon-local-network:
    driver: bridge

volumes:
  node-1-data:
  node-2-data:
  node-3-data:
  node-4-data:
  shared-data:
